### ISSUE TITLE
ICA_BASE_URL hard coded

### ISSUE THREAD

**Issue by alexiswl** [umccr/illumination#11]
ICA_BASE_URL is hard coded to "https://aps2.platform.illumina.com"

**Comment by pdiakumis** [comment]
@alexiswl what should that be? Do you mean it should be taken from an environment variable? i.e. `process.env.ICA_BASE_URL`?

**Comment by alexiswl** [comment]
Yes, but if not specified, falls back to `https://aps2.platform.illumina.com`
