### ISSUE TITLE
Consider AWS deployment options

### ISSUE THREAD

**Issue by pdiakumis** [umccr/illumination#2]

**Comment by pdiakumis** [comment]
@victorskl I take it illumination will become obsolete any minute (well, 'month') now, right? Will you be handling the GET endpoints in the portal?

**Comment by victorskl** [comment]
Yah Pete, consider `now() - 30 Nov 2019`; we should deploy this! But, yah, let have a quick chat this week to share notes and a way forward... @pdiakumis

**Comment by pdiakumis** [comment]
Awesome, sounds good!
